# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MNwZkYFTU62a-HpHmwmeaLHkI7rf567l
"""

pip install streamlit

import streamlit as st
import pickle
import pandas as pd

# Load model and columns
model = pickle.load(open('model.pkl', 'rb'))
columns = pickle.load(open('columns.pkl', 'rb'))

st.title("Car Price Prediction")

st.write("Fill details to predict car selling price")

# Inputs
year = st.number_input("Year of Purchase", 2000, 2025)
present_price = st.number_input("Present Price (Lakhs)")
kms_driven = st.number_input("Kilometers Driven")
owner = st.selectbox("Owner", [0, 1, 2, 3])

fuel_type = st.selectbox("Fuel Type", ["Petrol", "Diesel"])
seller_type = st.selectbox("Seller Type", ["Dealer", "Individual"])
transmission = st.selectbox("Transmission", ["Manual", "Automatic"])

# Input dictionary
input_dict = {
    'Year': year,
    'Present_Price': present_price,
    'Driven_kms': kms_driven,
    'Owner': owner,
    'Fuel_Type_Diesel': 1 if fuel_type == "Diesel" else 0,
    'Seller_Type_Individual': 1 if seller_type == "Individual" else 0,
    'Transmission_Manual': 1 if transmission == "Manual" else 0
}

input_df = pd.DataFrame([input_dict])
input_df = input_df.reindex(columns=columns, fill_value=0)

# Prediction
if st.button("Predict"):
    prediction = model.predict(input_df)
    st.success(f"Estimated Price: ₹ {prediction[0]:.2f} Lakhs")

