# -*- coding: utf-8 -*-
"""Car Price Prediction (ML Project_1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ReiSc7XMKEEzCmy4bwdBkMwQdLZ3eDXy

# Import Libraries
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

"""# Load Dataset"""

df = pd.read_csv("car data.csv")

df.head()

df.shape

df.info()

"""# Feature Engineering"""

df.describe()

# Check Missing Values
df.isnull().sum()

# Check Duplicate Rows
df.duplicated().sum()

df.drop_duplicates(inplace=True)

# distributuion of numerical features
df.hist(figsize=(10,8))
plt.show()

# Outlier Detection
plt.figure(figsize=(8,5))
sns.boxplot(df['Selling_Price'])
plt.show()

df = df[df['Selling_Price'] < 35]

# Categorical Feature Analysis
df['Fuel_Type'].value_counts().plot(kind='bar')
plt.show()

df['Transmission'].value_counts().plot(kind='bar')
plt.show()

# Correlation Analysis
plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='viridis')
plt.show()

df['car_age'] = 2025 - df['Year']
df.drop('Year', axis=1, inplace=True)
df.drop('Car_Name', axis=1, inplace=True)

# Encode Categorical Features
df = pd.get_dummies(df, drop_first=True)

"""# Define Features and Target"""

X = df.drop('Selling_Price', axis=1)
y = df['Selling_Price']

X, y

"""# Train Test Split"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""# Train Model"""

rf = RandomForestRegressor()

rf.fit(X_train, y_train)

"""# Prediction"""

y_pred = rf.predict(X_test)
y_pred

"""# Model Evaluation"""

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

"""# Hyperparameter Tuning"""

from sklearn.model_selection import RandomizedSearchCV

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Assuming X contains features for the pipeline
# Recreate the preprocessing steps that lead to the error
# You might need to adjust 'numerical_features' and 'categorical_features'
# based on the actual columns in X after feature engineering

# Define preprocessing steps
numerical_features = ['Present_Price', 'Kms_Driven', 'Owner', 'car_age']
categorical_features = ['Fuel_Type_Diesel', 'Fuel_Type_Petrol', 'Seller_Type_Individual', 'Transmission_Manual'] # Updated based on dummy variables

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore', drop='first'), categorical_features) # Using drop='first' consistent with get_dummies
    ])


# Create the pipeline with preprocessing and the regressor
rf = RandomForestRegressor(random_state=42) # Add random_state for reproducibility

pipeline = Pipeline(steps=[('preprocessing', preprocessor),
                           ('model', rf)])

param_grid = {
    'model__n_estimators':[100,200,300,400,500],
    'model__max_depth':[None,10,20,30,40],
    'model__min_samples_split':[2,5,10],
    'model__min_samples_leaf':[1,2,4],
    'model__max_features':['sqrt','log2']
    }

random_search = RandomizedSearchCV(
    estimator=pipeline,
    param_distributions=param_grid,
    n_iter=20,
    cv=5,
    scoring='r2',
    random_state=42,
    n_jobs=-1
    )

random_search.fit(X_train,y_train)

"""# Best Model"""

best_model = random_search.best_estimator_
print("Best Parameters:", random_search.best_params_)

"""# Final Prediction"""

final_pred = best_model.predict(X_test)
print("Final R2:", r2_score(y_test, final_pred)*100)

"""# Feature Importance"""

model = best_model.named_steps['model']
importances = model.feature_importances_
features = X.columns
importance_df = pd.DataFrame({"feature":features,
                              "importance":importances
                              })

print(importance_df.sort_values("importance",ascending=False))

"""# Predict New Car Price"""

prediction = best_model.predict(X_test)
print("Predicted Car Price:", prediction)

"""# Save Model"""

import pickle

pickle.dump(model, open('model.pkl', 'wb'))
pickle.dump(X.columns, open('columns.pkl', 'wb'))

